# 1-D array

In [1]:
import numpy as np
# Creating 1-D array
n_array = np.array([1,2,3,4,5])
print(n_array)

[1 2 3 4 5]


# 2-D array

In [2]:
import numpy as np
# Creating 2-D array
n_array = np.array([ [1,2,3,4,5],[5,4,3,2,1] ])
print(n_array)

[[1 2 3 4 5]
 [5 4 3 2 1]]


# Important Functions

In [3]:
import numpy as np

print("An Empty Array of size 5")
print(np.empty(5)) # Generate empty array of size 5
print("***")
print("An Array of only 1's of size 5")
print(np.ones(5)) # Generate array containing only 1's of size 5
print("***")
print("An Array of only 0's of size 5")
print(np.zeros(5)) # Generate array containing only 0's of size 5
print("***")
print("An Identity Matrix Array of size 5")
print(np.eye(5)) # Generate identity matrix array of size 5
print("***")
print("Array populated with numbers from 2 to 50 with the difference of 3")
print(np.arange(2, 50, 3)) # Generate array with consecutive numbers
print("***")

An Empty Array of size 5
[0. 0. 0. 0. 0.]
***
An Array of only 1's of size 5
[1. 1. 1. 1. 1.]
***
An Array of only 0's of size 5
[0. 0. 0. 0. 0.]
***
An Identity Matrix Array of size 5
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
***
Array populated with numbers from 2 to 50 with the difference of 3
[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]
***


# Indexing for a 1-D array

In [4]:
import numpy as np

arr = np.arange(0,10,1) # Generate array with numbers from 0 to 9
print("The Array")
print(arr)

print("\nElement at index 5")
print(arr[5]) # Fetch element at index 5

print("\nElements in a range of 0 to 6")
print(arr[0:6]) # Fetch elements in a range

arr[0:6] = 20 # Assign a value to a range of elements
print("\nNew array after changing elements in a range of 0 to 6")
print(arr)

The Array
[0 1 2 3 4 5 6 7 8 9]

Element at index 5
5

Elements in a range of 0 to 6
[0 1 2 3 4 5]

New array after changing elements in a range of 0 to 6
[20 20 20 20 20 20  6  7  8  9]


# Slicing 1-D array

In [5]:
import numpy as np

arr = np.arange(0,10,1)
print("The Array")
print(arr)

new_arr1 = arr[1:7] # This command selects a range of elements from the array
print("\nThe new sliced array")
print(new_arr1)

new_arr2 = arr[:] # This command selects all elements in the array
print("\nThe new sliced array with all elements")
print(new_arr2)

The Array
[0 1 2 3 4 5 6 7 8 9]

The new sliced array
[1 2 3 4 5 6]

The new sliced array with all elements
[0 1 2 3 4 5 6 7 8 9]


# Indexing for a 2-D array

In [6]:
import numpy as np
# Declare a 2-D array
arr2d = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
])
print("The Array")
print(arr2d)

print("\nElement at row 0 and column 1")
print(arr2d[0][1])

print("\nElements in a range of last two rows & columns")
print(arr2d[1:3, 1:3])

arr2d[1:3, 1:3] = 20
print("\nNew 2D array after changing last two rows & columns values")
print(arr2d)

The Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Element at row 0 and column 1
2

Elements in a range of last two rows & columns
[[5 6]
 [8 9]]

New 2D array after changing last two rows & columns values
[[ 1  2  3]
 [ 4 20 20]
 [ 7 20 20]]


# Slicing 2-D array

In [7]:
import numpy as np
# Declare a 2-D array
arr2d = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
])
print("The Array")
print(arr2d)

print("\nThe new sliced array")
print(arr2d[1:3, 0:2])

print("\nThe new sliced column")
print(arr2d[:, 1:2])

The Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]

The new sliced array
[[4 5]
 [7 8]]

The new sliced column
[[2]
 [5]
 [8]]


# The memory problem

In [8]:
import numpy as np

arr = np.arange(0,10,1)
print("The Array")
print(arr)

new_arr = arr[1:7]
print("\nThe new sliced array")
print(new_arr)

new_arr[:] = 20
print("\nThe Original array")
print(arr)

The Array
[0 1 2 3 4 5 6 7 8 9]

The new sliced array
[1 2 3 4 5 6]

The Original array
[ 0 20 20 20 20 20 20  7  8  9]


# Transpose

In [10]:
import numpy as np
# Creating 2-D array
arr = np.arange(0,50,1).reshape(10,5) # Declare a 2-D array

print("The original array")
print(arr)

print("\nThe transposed array")
print(arr.transpose()) # Print the transposed array
#print(arr.T) # This can also be used and same result will be produced

The original array
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]

The transposed array
[[ 0  5 10 15 20 25 30 35 40 45]
 [ 1  6 11 16 21 26 31 36 41 46]
 [ 2  7 12 17 22 27 32 37 42 47]
 [ 3  8 13 18 23 28 33 38 43 48]
 [ 4  9 14 19 24 29 34 39 44 49]]


# More ‘NumPy’ array functions

In [11]:
import numpy as np
# Declare 2 array
arr1 = np.arange(1,40,4)
arr2 = np.arange(1,30,3)

print("The first array\n", arr1, "\nThe second array\n", arr2, '\n')

print("The Exponent Function")
print(np.exp(arr1))

print("\nThe Square Function")
print(np.square(arr1))

print("\nThe Square root Function")
print(np.sqrt(arr1))

print("\nThe Cube root Function")
print(np.cbrt(arr1))

print("\nThe Addition Function")
print(np.add(arr1, arr2))

print("\nThe Subtraction Function")
print(np.subtract(arr1, arr2))

The first array
 [ 1  5  9 13 17 21 25 29 33 37] 
The second array
 [ 1  4  7 10 13 16 19 22 25 28] 

The Exponent Function
[2.71828183e+00 1.48413159e+02 8.10308393e+03 4.42413392e+05
 2.41549528e+07 1.31881573e+09 7.20048993e+10 3.93133430e+12
 2.14643580e+14 1.17191424e+16]

The Square Function
[   1   25   81  169  289  441  625  841 1089 1369]

The Square root Function
[1.         2.23606798 3.         3.60555128 4.12310563 4.58257569
 5.         5.38516481 5.74456265 6.08276253]

The Cube root Function
[1.         1.70997595 2.08008382 2.35133469 2.57128159 2.75892418
 2.92401774 3.07231683 3.20753433 3.33222185]

The Addition Function
[ 2  9 16 23 30 37 44 51 58 65]

The Subtraction Function
[0 1 2 3 4 5 6 7 8 9]


# NumPy where function

In [12]:
import numpy as np
# Declare 2 arrays
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([500, 600, 700, 800])

cond = np.array([False, True, False, True]) # Create an array with bool operators

res = np.where(cond, arr1, arr2) # apply the where condition
print(res)

[500  20 700  40]


# Some more NumPy functions for array

In [13]:
import numpy as np
# Declare 2 arrays of different types
arr1 = np.random.rand(7)
arr2 = np.array(['Dog', 'Cat', 'Lion', 'Dog', 'Eagle', 'Turtle', 'Lion'])

print("The original array")
print(arr1)

print("\nMean of all elements of array")
print(arr1.mean())

print("\nVariance of all elements of array")
print(arr1.var())

print("\nStandard Deviation of all elements of array")
print(arr1.std())

print("\nSum of all elements of array")
print(arr1.sum())

print("\nSorted array")
arr1.sort()
print(arr1)

print("\nOriginal array")
print(arr2)

print("\nUnique array")
print(np.unique(arr2))

The original array
[0.48152764 0.18230809 0.7620425  0.60116317 0.93354126 0.54145846
 0.52684799]

Mean of all elements of array
0.5755555870824021

Variance of all elements of array
0.04722953600173423

Standard Deviation of all elements of array
0.21732357442701478

Sum of all elements of array
4.028889109576815

Sorted array
[0.18230809 0.48152764 0.52684799 0.54145846 0.60116317 0.7620425
 0.93354126]

Original array
['Dog' 'Cat' 'Lion' 'Dog' 'Eagle' 'Turtle' 'Lion']

Unique array
['Cat' 'Dog' 'Eagle' 'Lion' 'Turtle']


# Array loading and saving

In [14]:
import numpy as np

arr1 = np.random.randn(7)

print("The original array:")
print(arr1)

np.save('saved_arr',arr1) # save the array 

arr2 = np.load('saved_arr.npy') # load the saved array from file

print("\nThe array loaded from file:")
print(arr2)

The original array:
[ 1.91315352  0.01707009 -2.60245144 -0.36805318  0.3674746   0.08395654
 -1.34780033]

The array loaded from file:
[ 1.91315352  0.01707009 -2.60245144 -0.36805318  0.3674746   0.08395654
 -1.34780033]


In [1]:
def getMinMax(arr):
  
    res = []
    
    for i in range(arr.shape[0]):
      
      res.append(arr[i].min())
      
      res.append(arr[i].max())
      
    return res

In [3]:
# Test Code
import numpy as np
arr = np.random.randint(1,100, size=(5,5))

print("The Original Array:")
print(arr)

res_arr = getMinMax(arr)

print("\nThe Resultnt list with min & max values:")
print(res_arr)

The Original Array:
[[77 91 28 29 91]
 [48 61 99 23 57]
 [17 89 87 53 94]
 [ 6 68 26 73 89]
 [19 24 39 39 41]]

The Resultnt list with min & max values:
[28, 91, 23, 99, 17, 94, 6, 89, 19, 41]
