# Numpy

In [3]:
import numpy

a_arr = numpy.array([1, 2, 3, 4, 5])
print(a_arr)

[1 2 3 4 5]


In [4]:
import numpy as np

a_arr = np.array([1, 2, 3, 4, 5])
print(a_arr)

[1 2 3 4 5]


In [5]:
print(np.__version__)

1.20.1


In [6]:
print(type(a_arr))

<class 'numpy.ndarray'>


In [7]:
an_r = np.array((1,2,3,4,5))
print(an_r)

[1 2 3 4 5]


In [8]:
# 0-D Array
a = np.array(30)
print(a)

30


In [9]:
# 1-D Array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [10]:
# 2-D Array
a = np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [12]:
# 3-D Array
a = np.array([[[1,3,2], [4,5,6],[2,1,2]]])
print(a)

[[[1 3 2]
  [4 5 6]
  [2 1 2]]]


In [13]:
#Check number Dimension

a = np.array([[[1,3,2], [4,5,6],[2,1,2]]])
print(a.ndim)

3


In [14]:
#Higer dim array

a = np.array([1,2,3,4], ndmin=5)
print(a)
print("The number of dimensions:", a.ndim)

[[[[[1 2 3 4]]]]]
The number of dimensions: 5


In [15]:
a = np.array([1,2,3,4])
print(a[0])
print(a[1])

1
2


In [18]:
# Access 2-D Arr
a = np.array([[10,20,30],[40,50,60]])
print("The second dim is ", a[0,1])

The second dim is  20


In [19]:
# Access 2-D Arr
a = np.array([[10,20,30],[40,50,60]])
print("The second dim is ", a[1,2])

The second dim is  60


In [21]:
# Access 3-D Arr
a = np.array([[[1,2,3],[4,5,6],[2,3,2],[6,7,8]]])
print("The second dim is ", a[0,1,2])

The second dim is  6


In [22]:
a_arr = np.array([1, 2, 3, 4, 5])
print(a_arr[1:4])

[2 3 4]


In [23]:
a_arr = np.array([1, 2, 3, 4, 5])
print(a_arr[:3])

[1 2 3]


In [24]:
a_arr = np.array([1, 2, 3, 4, 5])
print(a_arr[-4:])

[2 3 4 5]


In [25]:
a_arr = np.array([1, 2, 3, 4, 5])
print(a_arr[1:4:2])

[2 4]


# Slice 2-D

In [26]:
a = np.array([[1,2,3,4,5],[10,20,30,40,50]])
print(a[1,1:4])

[20 30 40]


In [27]:
print(a[0,1:4])

[2 3 4]


In [29]:
print(a[0:2, 1:4])

[[ 2  3  4]
 [20 30 40]]


In [30]:
m = np.array([1,2,3])
b = np.array(["banana", "fig", "watermelon"])

print(m.dtype)
print(b.dtype)

int32
<U10


In [31]:
m = np.array([1,2,3])
b = np.array(["banana", "fig", "watermelon"], dtype = "S")

print(m.dtype)
print(b.dtype)

int32
|S10


# Numpy Operation

In [32]:
a = np.array([1,2,3,4])
b = a + 2
print(b)

[3 4 5 6]


In [33]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
c = a + b
print(c)

[2 4 6 8]


In [34]:
a = np.array([1,2,3,4])
b = 4 * a
print(b)

[ 4  8 12 16]


In [35]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
np.dot(a,b)

30

In [36]:
a = np.array([1,2,3,4])
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])